### ISSUE TITLE
Set up the Attendance Manager database

### ISSUE THREAD

**Issue by mayank8318** [Njack-IITP/IITP-Connect#15]
Make database for the attendance manager.

**Comment by dr0pdb** [comment]
@mayank8318 I would suggest working on this after the completion of the coding calendar, since it would also require database and hence it would be very easy after that to extend it for Attendance Manager

**Comment by dr0pdb** [comment]
@mayank8318 @arundhati24 I would like to discuss an important point here. The ```CodingCalendar``` uses SQlite database i.e. ```ContentProviders```. Now that we have a new Library ```Room```, how should we go about making the database for future modules. If we continue to use ```ContentProviders``` then that would mean we won't be using new standards but if we use ```Room``` , we will have to refactor ```CodingCalendar``` since we can't have both ```Room``` and ```ContentProvider``` at the same time. 
Views ?

**Comment by dr0pdb** [comment]
In my View, we can keep using ContentProviders for now, since the release is a priority. Once we get the app to a release state, we can change it to use Room.
Suggestions ?
